version: '3.8'

services:
  # Supabase Database
  supabase-db:
    image: supabase/postgres:15.1.0.117
    environment:
      POSTGRES_DB: vindexchain
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your-super-secret-jwt-token-with-at-least-32-characters-long
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - vindexchain-network

  # VindexChain Core Node
  vindexchain-core:
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    ports:
      - "26656:26656"  # P2P
      - "26657:26657"  # RPC
      - "1317:1317"    # REST API
    environment:
      - NODE_ENV=development
      - DB_HOST=supabase-db
      - DB_PORT=5432
      - DB_NAME=vindexchain
      - DB_USER=postgres
      - DB_PASSWORD=your-super-secret-jwt-token-with-at-least-32-characters-long
    depends_on:
      - supabase-db
    networks:
      - vindexchain-network
    volumes:
      - node_data:/app/data

  # Block Explorer
  vindexscan:
    build:
      context: ./explorer
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://vindexchain-core:1317
      - NEXT_PUBLIC_WS_URL=ws://vindexchain-core:26657/websocket
      - DATABASE_URL=postgresql://postgres:your-super-secret-jwt-token-with-at-least-32-characters-long@supabase-db:5432/vindexchain
    depends_on:
      - vindexchain-core
      - supabase-db
    networks:
      - vindexchain-network

  # BurnSwap DEX
  burnswap:
    build:
      context: ./dex
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://vindexchain-core:1317
      - NEXT_PUBLIC_EXPLORER_URL=http://vindexscan:3000
      - DATABASE_URL=postgresql://postgres:your-super-secret-jwt-token-with-at-least-32-characters-long@supabase-db:5432/vindexchain
    depends_on:
      - vindexchain-core
      - supabase-db
    networks:
      - vindexchain-network

  # Website
  vindexchain-website:
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_EXPLORER_URL=http://localhost:3001
      - NEXT_PUBLIC_DEX_URL=http://localhost:3002
    networks:
      - vindexchain-network

  # Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - vindexchain-network
    volumes:
      - redis_data:/data

networks:
  vindexchain-network:
    driver: bridge

volumes:
  db_data:
  node_data:
  redis_data: